import { LoginApi, ResetPwdApi } from './apis/LoginApi'
import { RegistrationApi } from './apis/RegistrationApi'
import { GetActivityPoolApi, GetActivityApi } from './apis/GetActivityPoolAPI'
import {
    GetFolderApi,
    CreateFolderApi,
    GetRealmApi,
    CreateRealmApi,
    GetTopicApi,
    CreateTopicApi,
    GetKeyConceptApi,
    CreateKeyConceptApi,
    GetPurposeApi,
    CreatePurposeApi,
    GetAgeRangeApi,
    CreateAgeRangeApi,
    GetScientistApi,
    CreateScientistApi,
    GetFieldApi,
    CreateFieldApi,
    GetInstitutionApi,
    CreateInstitutionApi,
    GetCountryApi,
    CreateCountryApi,
} from './apis/GetMappingFormFields'
import { NewActivityApi } from './apis/NewActivity'
import { UploadFileApi, DownloadFileApi } from './apis/UploadFile'
import { GetCurriculumApi, MapCurriculumApi } from './apis/MapCurriculumAPI'

export {
    LoginApi,
    ResetPwdApi,
    RegistrationApi,
    GetActivityPoolApi,
    GetActivityApi,
    GetFolderApi,
    CreateFolderApi,
    GetRealmApi,
    CreateRealmApi,
    GetTopicApi,
    CreateTopicApi,
    GetKeyConceptApi,
    GetPurposeApi,
    GetAgeRangeApi,
    CreateKeyConceptApi,
    CreatePurposeApi,
    CreateAgeRangeApi,
    NewActivityApi,
    UploadFileApi,
    GetScientistApi,
    CreateScientistApi,
    GetFieldApi,
    CreateFieldApi,
    GetInstitutionApi,
    CreateInstitutionApi,
    GetCountryApi,
    CreateCountryApi,
    GetCurriculumApi,
    MapCurriculumApi,
    DownloadFileApi,
}
